# Generated by Django 3.2.5 on 2022-07-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registraduria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='apellido', max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(db_column='telefono', max_length=10, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
                'db_table': 'lider',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('id_fk_departamento', models.ForeignKey(db_column='id_fk_departamento', on_delete=django.db.models.deletion.PROTECT, to='registraduria.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(db_column='direccion', max_length=100, verbose_name='Direccion')),
                ('id_fk_municipio', models.ForeignKey(db_column='id_fk_municipio', on_delete=django.db.models.deletion.PROTECT, to='registraduria.municipio')),
            ],
            options={
                'verbose_name': 'Puesto votación',
                'verbose_name_plural': 'Puestos de votación',
                'db_table': 'puesto_votacion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'LIDER')], default=1),
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='apellido', max_length=50, verbose_name='Apellido')),
                ('direccion', models.CharField(db_column='direccion', max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(db_column='telefono', max_length=10, verbose_name='Teléfono')),
                ('cedula', models.CharField(db_column='cedula', max_length=10, verbose_name='Cédula')),
                ('mesa', models.IntegerField(blank=True, db_column='mesa', null=True, verbose_name='Mesa')),
                ('id_fk_barrio', models.ForeignKey(db_column='id_fk_barrio', on_delete=django.db.models.deletion.PROTECT, to='registraduria.barrio')),
                ('id_fk_lider', models.ForeignKey(db_column='id_fk_lider', on_delete=django.db.models.deletion.PROTECT, to='registraduria.lider')),
                ('id_fk_puesto_votacion', models.ForeignKey(db_column='id_fk_puesto_votacion', on_delete=django.db.models.deletion.PROTECT, to='registraduria.puestovotacion')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
                'db_table': 'votante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('id_fk_municipio', models.ForeignKey(db_column='id_fk_municipio', on_delete=django.db.models.deletion.PROTECT, to='registraduria.municipio')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='barrio',
            name='id_fk_comuna',
            field=models.ForeignKey(db_column='id_fk_comuna', on_delete=django.db.models.deletion.PROTECT, to='registraduria.comuna'),
        ),
    ]
