# Generated by Django 3.2.5 on 2022-07-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registraduria', '0002_auto_20220704_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestovotacion',
            name='id_fk_usuario',
            field=models.ForeignKey(db_column='id_fk_usuario', default=2, on_delete=django.db.models.deletion.PROTECT, to='registraduria.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, db_column='direccion', max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_fk_municipio',
            field=models.ForeignKey(db_column='id_fk_municipio', default=3, on_delete=django.db.models.deletion.PROTECT, to='registraduria.municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'LIDER')], default=2),
        ),
    ]
