# Generated by Django 3.2.5 on 2022-07-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registraduria', '0003_auto_20220705_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_fk_municipio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
