# Generated by Django 3.2.5 on 2022-07-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registraduria', '0005_auto_20220705_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_fk_usuario', models.ForeignKey(db_column='id_fk_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_fk_votante', models.ForeignKey(db_column='id_fk_votante', on_delete=django.db.models.deletion.PROTECT, to='registraduria.votante')),
            ],
            options={
                'verbose_name': 'traza',
                'verbose_name_plural': 'trazas',
                'db_table': 'traza',
                'ordering': ['id'],
            },
        ),
    ]
