# Generated by Django 3.2.5 on 2022-07-05 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registraduria', '0006_traza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traza',
            name='id_fk_usuario',
            field=models.ForeignKey(db_column='id_fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traza',
            name='id_fk_votante',
            field=models.ForeignKey(db_column='id_fk_votante', on_delete=django.db.models.deletion.DO_NOTHING, to='registraduria.votante'),
        ),
    ]
